language: android
dist: trusty
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "build-tools;29.0.2"
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew jacocoTestDebugbtDebugUnitTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
