name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Generage JaCoCo report
        run: ./gradlew jacocoTestDebugbtDebugUnitTestReport
      - name: Send JaCoCo coverage report to Codecov
        uses: codecov/codecov-action@v1
